### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by GabrielMajeri** [zowens/crc32c#3]
[Travis](https://travis-ci.com/) provides free CI for open-source projects. They also have a guide for [setting it up](https://docs.travis-ci.com/user/languages/rust/).

A simple `.travis.yml` could be

```yaml
language: rust
rust:
  - nightly # Require nightly, since we need some unstable features.
cache: cargo
```
